name: Generate contract baseline

on:
  workflow_dispatch:

env:
  PHIO_CONTRACT_POLICY: HONEST
  PHIO_TAU_POLICY: AT_LEAST_ONE
  PHIO_ALLOW_EXEC_EXTRACTION: "false"
  PHIO_UPDATE_BASELINE: "true"

permissions:
  contents: write

jobs:
  baseline:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install pytest

      - name: Generate baseline via final_validation
        env:
          PHIO_INSTRUMENT: "phi_otimes_o_instrument_v0_1.py"
        run: |
          chmod +x final_validation.sh validate_contract_warnings.sh || true
          ./final_validation.sh

      - name: Commit baseline
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .contract/contract_baseline.json
          git commit -m "Update contract baseline" || echo "No changes"
          git push
